### ISSUE TITLE
 [Issue] Bundle generator is borked.

### ISSUE THREAD

**Issue by eris-webserv** [Nixinova/Website#11]
The bundle generator copies the first item (no 1) to ALL slots, regardless of there being something already inputted.

**Comment by Nixinova** [comment]
Can you attach a screenshot? The items are assigned correctly for me.

<img width=600 src="https://user-images.githubusercontent.com/42429413/123525275-84fe0800-d723-11eb-948a-9cb715349965.png">

**Comment by eris-webserv** [comment]
Oh, nevermind. I assumed those numbers in the grid were the amount, not the
item.
